const productImages: Record<string, string> = {
  "Trail Ridge Mountain Cycle": "/catalog/products/trail-ridge-mountain-cycle.png",
  "Summit Path Mountain Cycle": "/catalog/products/summit-path-mountain-cycle.png",
  "Rock Trail Sport Cycle": "/catalog/products/rock-trail-sport-cycle.png",
  "Aero Line Road Cycle": "/catalog/products/aero-line-road-cycle.png",
  "Endurance Flow Road Cycle": "/catalog/products/endurance-flow-road-cycle.png",
  "Velocity Commuter Road Cycle": "/catalog/products/velocity-commuter-road-cycle.png",
  "City Trail Hybrid Cycle": "/catalog/products/city-trail-hybrid-cycle.png",
  "Urban Comfort Hybrid Cycle": "/catalog/products/urban-comfort-hybrid-cycle.png",
  "Metro Glide Hybrid Cycle": "/catalog/products/metro-glide-hybrid-cycle.png",
  "Cycle Saddle Storage Bag": "/catalog/products/cycle-saddle-storage-bag.png",
  "Cycle Frame Storage Pouch": "/catalog/products/cycle-frame-storage-pouch.png",
  "Cycle Handlebar Carry Bag": "/catalog/products/cycle-handlebar-carry-bag.png",
  "Bright Beam Front Light": "/catalog/products/bright-beam-front-light.png",
  "Wide Glow Handlebar Light": "/catalog/products/wide-glow-handlebar-light.png",
  "Compact Safety Light Set": "/catalog/products/compact-safety-light-set.png",
  "Secure U-Lock": "/catalog/products/secure-u-lock.png",
  "Heavy Guard Frame Lock": "/catalog/products/heavy-guard-frame-lock.png",
  "Compact Cable Lock": "/catalog/products/compact-cable-lock.png",
  "Smooth Roll Road Tire": "/catalog/products/smooth-roll-road-tire.png",
  "Puncture Guard Touring Tire": "/catalog/products/puncture-guard-touring-tire.png",
  "Grip Trail Mountain Tire": "/catalog/products/grip-trail-mountain-tire.png",
  "Hydraulic Disc Brake Set": "/catalog/products/hydraulic-disc-brake-set.png",
  "Trail Control Brake Kit": "/catalog/products/trail-control-brake-kit.png",
  "Mechanical Brake Caliper Pair": "/catalog/products/mechanical-brake-caliper-pair.png",
  "Smooth Shift Chain": "/catalog/products/smooth-shift-chain.png",
  "Trail Strength Chain": "/catalog/products/trail-strength-chain.png",
  "Urban Drive Chain": "/catalog/products/urban-drive-chain.png",
  "Smooth Ratio Gear Cassette": "/catalog/products/smooth-ratio-gear-cassette.png",
  "Trail Climb Gear Set": "/catalog/products/trail-climb-gear-set.png",
  "Precision Shift Derailleur": "/catalog/products/precision-shift-derailleur.png",
};

const image = (label: string) => {
  const imagePath = productImages[label];

  return [imagePath, imagePath, imagePath, imagePath, imagePath];
};

const productCatalog = [
  {
    id: 1,
    name: "Trail Ridge Mountain Cycle",
    category: "Cycles",
    subcategory: "Mountain Bikes",
    price: 499,
    stock: 0,
    shortDescription: "Durable mountain cycle for rough trails and weekend rides.",
    detailedDescription: "A sturdy off-road cycle with responsive suspension, wide tires, and confident control for uneven paths, gravel tracks, and hill routes.",
    images: image("Trail Ridge Mountain Cycle"),
  },
  {
    id: 2,
    name: "Summit Path Mountain Cycle",
    category: "Cycles",
    subcategory: "Mountain Bikes",
    price: 650,
    stock: 0,
    shortDescription: "Balanced trail cycle for climbing, cornering, and daily adventure.",
    detailedDescription: "Built with a lightweight frame, front suspension, and dependable gearing for riders who want comfort and grip on mixed off-road terrain.",
    images: image("Summit Path Mountain Cycle"),
  },
  {
    id: 3,
    name: "Rock Trail Sport Cycle",
    category: "Cycles",
    subcategory: "Mountain Bikes",
    price: 700,
    stock: 0,
    shortDescription: "Sport-focused mountain cycle with stable handling.",
    detailedDescription: "Designed for technical paths and forest trails, this cycle offers responsive steering, strong braking, and a comfortable riding position.",
    images: image("Rock Trail Sport Cycle"),
  },
  {
    id: 5,
    name: "Aero Line Road Cycle",
    category: "Cycles",
    subcategory: "Road Bikes",
    price: 920,
    stock: 0,
    shortDescription: "Fast road cycle for smooth pavement and long-distance riding.",
    detailedDescription: "A lightweight road cycle shaped for speed, steady handling, and efficient power transfer across city roads, open routes, and fitness rides.",
    images: image("Aero Line Road Cycle"),
  },
  {
    id: 6,
    name: "Endurance Flow Road Cycle",
    category: "Cycles",
    subcategory: "Road Bikes",
    price: 900,
    stock: 0,
    shortDescription: "Comfortable road cycle for longer rides.",
    detailedDescription: "Built for balanced speed and comfort, this road cycle supports relaxed posture, smooth rolling, and dependable control over extended distances.",
    images: image("Endurance Flow Road Cycle"),
  },
  {
    id: 7,
    name: "Velocity Commuter Road Cycle",
    category: "Cycles",
    subcategory: "Road Bikes",
    price: 840,
    stock: 0,
    shortDescription: "Quick and efficient cycle for roads and daily travel.",
    detailedDescription: "A responsive road cycle with narrow tires, clean geometry, and reliable parts for fast commutes and steady fitness sessions.",
    images: image("Velocity Commuter Road Cycle"),
  },
  {
    id: 9,
    name: "City Trail Hybrid Cycle",
    category: "Cycles",
    subcategory: "Hybrid Bikes",
    price: 600,
    stock: 0,
    shortDescription: "Versatile hybrid cycle for city roads and light trails.",
    detailedDescription: "Combines upright comfort, efficient tires, and practical handling for riders who move between commuting, errands, and casual weekend routes.",
    images: image("City Trail Hybrid Cycle"),
  },
  {
    id: 10,
    name: "Urban Comfort Hybrid Cycle",
    category: "Cycles",
    subcategory: "Hybrid Bikes",
    price: 550,
    stock: 0,
    shortDescription: "Comfortable hybrid cycle for everyday travel.",
    detailedDescription: "A smooth and stable hybrid cycle with relaxed geometry, easy control, and reliable parts for daily local rides.",
    images: image("Urban Comfort Hybrid Cycle"),
  },
  {
    id: 11,
    name: "Metro Glide Hybrid Cycle",
    category: "Cycles",
    subcategory: "Hybrid Bikes",
    price: 700,
    stock: 0,
    shortDescription: "Agile hybrid cycle for active city riders.",
    detailedDescription: "Made for riders who want a confident city cycle with balanced speed, comfort, and dependable handling on varied surfaces.",
    images: image("Metro Glide Hybrid Cycle"),
  },
  {
    id: 13,
    name: "Cycle Saddle Storage Bag",
    category: "Accessories",
    subcategory: "Cycle Bags",
    price: 35,
    stock: 0,
    shortDescription: "Small saddle bag for tools, keys, and ride essentials.",
    detailedDescription: "A compact under-seat cycle bag with secure straps, tidy internal space, and enough room for basic tools, tubes, and small personal items.",
    images: image("Cycle Saddle Storage Bag"),
  },
  {
    id: 14,
    name: "Cycle Frame Storage Pouch",
    category: "Accessories",
    subcategory: "Cycle Bags",
    price: 42,
    stock: 0,
    shortDescription: "Slim frame pouch for snacks, phone, and repair items.",
    detailedDescription: "A stable frame-mounted storage pouch that keeps frequently used items close while preserving comfortable pedaling space.",
    images: image("Cycle Frame Storage Pouch"),
  },
  {
    id: 15,
    name: "Cycle Handlebar Carry Bag",
    category: "Accessories",
    subcategory: "Cycle Bags",
    price: 58,
    stock: 0,
    shortDescription: "Front bag for maps, layers, and ride accessories.",
    detailedDescription: "A weather-resistant handlebar bag with practical capacity, easy access, and a secure mount for commuting or longer weekend rides.",
    images: image("Cycle Handlebar Carry Bag"),
  },
  {
    id: 17,
    name: "Bright Beam Front Light",
    category: "Accessories",
    subcategory: "Lights",
    price: 45,
    stock: 0,
    shortDescription: "Powerful front light for evening and low-light riding.",
    detailedDescription: "A rechargeable front cycle light with multiple brightness modes and a quick-fit mount for improved visibility on darker routes.",
    images: image("Bright Beam Front Light"),
  },
  {
    id: 18,
    name: "Wide Glow Handlebar Light",
    category: "Accessories",
    subcategory: "Lights",
    price: 55,
    stock: 0,
    shortDescription: "Wide-beam light for clear forward visibility.",
    detailedDescription: "Designed to brighten the road ahead with a broad beam pattern, durable casing, and easy handlebar attachment.",
    images: image("Wide Glow Handlebar Light"),
  },
  {
    id: 19,
    name: "Compact Safety Light Set",
    category: "Accessories",
    subcategory: "Lights",
    price: 35,
    stock: 0,
    shortDescription: "Front and rear light set for everyday safety.",
    detailedDescription: "A compact light pair with simple mounting, flashing modes, and rechargeable convenience for commuting and casual cycling.",
    images: image("Compact Safety Light Set"),
  },
  {
    id: 21,
    name: "Secure U-Lock",
    category: "Accessories",
    subcategory: "Locks",
    price: 70,
    stock: 0,
    shortDescription: "Strong U-lock for everyday cycle security.",
    detailedDescription: "A hardened lock with a sturdy shackle and simple key operation, designed for securing cycles during errands and daily parking.",
    images: image("Secure U-Lock"),
  },
  {
    id: 22,
    name: "Heavy Guard Frame Lock",
    category: "Accessories",
    subcategory: "Locks",
    price: 90,
    stock: 0,
    shortDescription: "Durable lock for higher-security parking needs.",
    detailedDescription: "A tough cycle lock with reinforced construction and reliable locking action for busy streets, storage rooms, and shared parking.",
    images: image("Heavy Guard Frame Lock"),
  },
  {
    id: 23,
    name: "Compact Cable Lock",
    category: "Accessories",
    subcategory: "Locks",
    price: 30,
    stock: 0,
    shortDescription: "Flexible cable lock for quick stops.",
    detailedDescription: "A lightweight lock with flexible reach, useful for short stops, secondary security, and locking accessories with the cycle.",
    images: image("Compact Cable Lock"),
  },
  {
    id: 25,
    name: "Smooth Roll Road Tire",
    category: "Spare Parts",
    subcategory: "Tires",
    price: 50,
    stock: 0,
    shortDescription: "Fast rolling tire for paved roads.",
    detailedDescription: "A road-focused tire with low rolling resistance, steady grip, and durable casing for training, commuting, and longer rides.",
    images: image("Smooth Roll Road Tire"),
  },
  {
    id: 26,
    name: "Puncture Guard Touring Tire",
    category: "Spare Parts",
    subcategory: "Tires",
    price: 55,
    stock: 0,
    shortDescription: "Durable tire with added puncture resistance.",
    detailedDescription: "A reliable tire built for commuting and touring, with reinforced protection and confident traction across everyday surfaces.",
    images: image("Puncture Guard Touring Tire"),
  },
  {
    id: 27,
    name: "Grip Trail Mountain Tire",
    category: "Spare Parts",
    subcategory: "Tires",
    price: 65,
    stock: 0,
    shortDescription: "Aggressive tread tire for loose and rough trails.",
    detailedDescription: "A mountain tire with deep tread blocks for stronger cornering grip, braking control, and traction on technical paths.",
    images: image("Grip Trail Mountain Tire"),
  },
  {
    id: 29,
    name: "Hydraulic Disc Brake Set",
    category: "Spare Parts",
    subcategory: "Brakes",
    price: 100,
    stock: 0,
    shortDescription: "Reliable disc brake set for controlled stopping.",
    detailedDescription: "A complete hydraulic-style brake set designed for consistent stopping power, steady modulation, and everyday riding confidence.",
    images: image("Hydraulic Disc Brake Set"),
  },
  {
    id: 30,
    name: "Trail Control Brake Kit",
    category: "Spare Parts",
    subcategory: "Brakes",
    price: 120,
    stock: 0,
    shortDescription: "Strong brake kit for trail and utility cycles.",
    detailedDescription: "A performance-minded brake kit with responsive lever feel and dependable control across fast descents and wet city streets.",
    images: image("Trail Control Brake Kit"),
  },
  {
    id: 31,
    name: "Mechanical Brake Caliper Pair",
    category: "Spare Parts",
    subcategory: "Brakes",
    price: 75,
    stock: 0,
    shortDescription: "Simple mechanical calipers for easy maintenance.",
    detailedDescription: "A practical brake caliper pair with straightforward adjustment, steady stopping, and compatibility for everyday service work.",
    images: image("Mechanical Brake Caliper Pair"),
  },
  {
    id: 33,
    name: "Smooth Shift Chain",
    category: "Spare Parts",
    subcategory: "Chains",
    price: 32,
    stock: 0,
    shortDescription: "Reliable replacement chain for smooth gear changes.",
    detailedDescription: "A durable cycle chain with clean shifting behavior and corrosion-resistant finish for routine drivetrain replacement.",
    images: image("Smooth Shift Chain"),
  },
  {
    id: 34,
    name: "Trail Strength Chain",
    category: "Spare Parts",
    subcategory: "Chains",
    price: 40,
    stock: 0,
    shortDescription: "Strong chain for off-road and high-load riding.",
    detailedDescription: "Built for dependable power transfer on rougher rides, this chain supports confident pedaling and long service intervals.",
    images: image("Trail Strength Chain"),
  },
  {
    id: 35,
    name: "Urban Drive Chain",
    category: "Spare Parts",
    subcategory: "Chains",
    price: 28,
    stock: 0,
    shortDescription: "Everyday chain for commuting and city cycles.",
    detailedDescription: "A practical replacement chain for daily riding, offering smooth operation, easy installation, and reliable drivetrain feel.",
    images: image("Urban Drive Chain"),
  },
  {
    id: 37,
    name: "Smooth Ratio Gear Cassette",
    category: "Spare Parts",
    subcategory: "Gears",
    price: 68,
    stock: 0,
    shortDescription: "Replacement gear cassette for smooth speed changes.",
    detailedDescription: "A multi-speed cassette designed for consistent shifting, reliable chain engagement, and balanced climbing and cruising ratios.",
    images: image("Smooth Ratio Gear Cassette"),
  },
  {
    id: 38,
    name: "Trail Climb Gear Set",
    category: "Spare Parts",
    subcategory: "Gears",
    price: 85,
    stock: 0,
    shortDescription: "Wide-range gear set for hills and rougher rides.",
    detailedDescription: "A wide-range gear setup that gives riders easier climbing options, steady cadence control, and dependable trail performance.",
    images: image("Trail Climb Gear Set"),
  },
  {
    id: 39,
    name: "Precision Shift Derailleur",
    category: "Spare Parts",
    subcategory: "Gears",
    price: 74,
    stock: 0,
    shortDescription: "Rear shifting unit for crisp gear movement.",
    detailedDescription: "A precise rear derailleur built for clean shifts, stable chain management, and everyday drivetrain servicing.",
    images: image("Precision Shift Derailleur"),
  },
];

export const products = productCatalog.map((product) => ({
  ...product,
  basePrice: product.price,
}));
